version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'ce:2c:9f:cb:87:9f:50:ad:8e:70:cf:f4:e2:d1:dd:ab'
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
